### ISSUE TITLE
ordering of link writing

### ISSUE THREAD

**Issue by EddieGarmon** [ThatRendle/Simple.Web#64]
should links be written in an alpha-numeric order on the href element for consistency and the ability to ensure in testing that all links are correct not just the count of them?

**Comment by ThatRendle** [comment]
I'm not really convinced of the use of that other than in testing, and I don't want the overhead of sorting in production.

One thing I'm considering is redoing the format of the links in JSON so that instead of an array it's a hash, with the rel as the key, or indeed allowing a link formatter to be injected by the developer to format the list as required.

**Comment by EddieGarmon** [comment]
Non-deterministic ordering really makes validation 'clumsy' as you get the output, then sort yourself, then do the validation. and a quicksort isn't nearly as expensive as all the reflection going on in DataContractSerializer.

Maybe just a SortLinks extension method in the test helpers for now?

I do like the notion of a custom link writer, makes me think of `IConvertBetween<TModel, TSerialized>` as a more generic `IConvertXmlFor<TModel>`

**Comment by EddieGarmon** [comment]
seems to be a non major issue in my testing
